##
## Makefile<2> for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Wed Feb 12 20:30:30 2014 laurent ansel
## Last update Wed Feb 12 20:32:02 2014 laurent ansel
##

SRCSERVER +=		$(TRADE)/TradeManager.cpp	\
			$(TRADE)/Trade.cpp
