##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Mon Feb 10 11:43:26 2014 antoine maitre
##

SRCCOMMON+=		$(BATTLE)/Battle.cpp
SRCCOMMON+=		$(BATTLE)/BattleUpdater.cpp
SRCCOMMON+=		$(BATTLE)/BattleManager.cpp
