##
## Makefile<3> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 15:43:44 2013 laurent ansel
## Last update Wed Jan 29 16:21:13 2014 antoine maitre
##

SRCSERVER +=	$(BATTLESERV)/BattleUpdater.cpp
SRCSERVER +=	$(BATTLESERV)/BattleManager.cpp
