##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:57:56 2013 laurent ansel
## Last update Tue Dec 10 09:09:53 2013 laurent ansel
##

SRCCOMMON +=			$(CRYPTO)/Crypto.cpp

LDFLAGS +=			-lcryptopp
