##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Feb  6 12:54:07 2014 laurent ansel
## Last update Thu Feb  6 12:54:29 2014 laurent ansel
##

SRCSERVER +=	$(CLIENTWRITER)/ClientWriter.cpp
