##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Wed Jan 29 16:09:45 2014 antoine maitre
##

SRCCOMMON+=		$(BATTLE)/Battle.cpp
