##
## Makefile<2> for Battle in /home/mestag_a/Documents/Projets/Tek3/PFA/linumon/MMO
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Tue Mar 25 14:37:56 2014 alexis mestag
## Last update Tue Mar 25 14:43:09 2014 alexis mestag
##

BATTLE_SRC=		BattleParams.cpp

BATTLE_SRC:=		$(addprefix $(BATTLE)/,$(BATTLE_SRC))

SRCCOMMON+=		$(BATTLE_SRC)
