##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Feb 25 14:27:14 2014 laurent ansel
## Last update Tue Feb 25 14:27:42 2014 laurent ansel
##

SRCSERVER +=	$(PNJMANAGER)/PNJManager.cpp
