##
## Makefile for  in /home/maresc_g/Projets/en_cours/linumon/MMO
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Jan 24 11:13:21 2014 guillaume marescaux
## Last update Fri Jan 24 13:20:50 2014 guillaume marescaux
##

CLIENT_INCLUDES=	-I $(CLIENT)/include

CLIENT_SRC=		$(CLIENT)/src

include			$(CLIENT_SRC)/Makefile
