##
## Makefile<2> for test in /home/mestag_a/Documents/Projets/Tek3/Babel/Common
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Mon Nov 25 22:42:22 2013 alexis mestag
## Last update Tue Nov 26 00:30:34 2013 alexis mestag
##

MUTEX=			$(SRCDIR)/Mutex
FILESYSTEM=		$(SRCDIR)/FileSystem
THREAD=			$(SRCDIR)/Thread

include			$(MUTEX)/Makefile
include			$(FILESYSTEM)/Makefile
include			$(THREAD)/Makefile
