##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Fri Nov 29 14:41:58 2013 laurent ansel
##

SRCCOMMON+=		$(TRAME)/Trame.cpp

