##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Thu Jan 30 11:22:16 2014 laurent ansel
##

SRCCOMMON+=		$(TRAME)/Trame.cpp

