##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:57:56 2013 laurent ansel
## Last update Thu Nov 28 19:27:00 2013 laurent ansel
##

SRCCOMMON +=			$(POLL)/UnixPoll.cpp

