##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Feb  6 14:03:36 2014 laurent ansel
## Last update Thu Mar 13 20:23:02 2014 laurent ansel
##

SRCSERVER +=		$(GAMEPROTOCOL)/GameProtocol.cpp	\
			$(GAMEPROTOCOL)/StuffActions.cpp	\
			$(GAMEPROTOCOL)/Interaction.cpp		\
			$(GAMEPROTOCOL)/InventoryManager.cpp	\
			$(GAMEPROTOCOL)/JobManager.cpp		\
			$(GAMEPROTOCOL)/OtherCommand.cpp	\
			$(GAMEPROTOCOL)/TalentManager.cpp	\
			$(GAMEPROTOCOL)/GuildManager.cpp	\
			$(GAMEPROTOCOL)/DigitaliserManager.cpp
