##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Feb  6 14:03:36 2014 laurent ansel
## Last update Thu Feb  6 14:26:33 2014 laurent ansel
##

SRCSERVER +=	$(GAMEPROTOCOL)/GameProtocol.cpp
