##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Feb 17 14:49:07 2014 laurent ansel
## Last update Tue Feb 18 11:19:38 2014 laurent ansel
##

SRCSERVER +=	$(RESSOURCEMANAGER)/RessourceManager.cpp

LDFLAGS +=	-lboost_system
