##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:57:56 2013 laurent ansel
## Last update Fri Nov 29 15:35:32 2013 laurent ansel
##

SRCCOMMON +=			$(CIRCULAR_BUFFER_MANAGER)/CircularBufferManager.cpp \
				$(CIRCULAR_BUFFER_MANAGER)/CircularBuffer.cpp

