##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/linumon/MMO
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Jan 24 14:00:32 2014 guillaume marescaux
## Last update Fri Jan 24 14:00:40 2014 guillaume marescaux
##

SRCCLIENT +=		$(CORE)/Core.cpp
