##
## Makefile for  in /home/ansel_l/Documents/Pfa/work/Server/include
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sun Dec  1 14:59:50 2013 laurent ansel
## Last update Thu Feb  6 14:26:14 2014 laurent ansel
##

SRCSERVER +=	$(CODEBREAKER)/CodeBreaker.cpp
