##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Tue Nov 26 00:53:19 2013 alexis mestag
##

SRCCOMMON+=		$(MUTEX)/AMutex.cpp		\
			$(MUTEX)/UnixMutex.cpp

LDFLAGS+=		-lpthread -D_REENTRANT
