##
## Makefile<3> for  in /home/ansel_l/Documents/Pfa/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Fri Jan 24 13:31:15 2014 laurent ansel
## Last update Fri Jan 24 13:31:30 2014 laurent ansel
##

SRCCOMMON +=			$(PROTOCOL)/Protocol.cpp
