##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Sun Mar  2 22:34:24 2014 antoine maitre
##

SRCCOMMON+=		$(AI)/AI.cpp
