##
## Makefile<2> for Rtype in /home/mestag_a/Documents/Projets/Tek3/RType/rtype/rtype/Server/src
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Sat Nov  2 18:00:02 2013 alexis mestag
## Last update Mon Feb 10 13:40:07 2014 laurent ansel
##

SRCCOMMON +=	$(DYNAMICLIBRARY)/UnixDynamicLibrary.cpp	\
		$(DYNAMICLIBRARY)/ADynamicLibrary.cpp		\
		$(DYNAMICLIBRARY)/DynamicLibrary.cpp

LDFLAGS	+=	-ldl
