##
## Makefile<3> for Makefile in /home/mestag_a/Documents/Projets/Tek3/PFA/linumon/MMO
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Tue Dec  3 10:53:24 2013 alexis mestag
## Last update Tue Dec  3 10:55:36 2013 alexis mestag
##

UTILITY_SRC=		Id.cpp		\
			Nameable.cpp

UTILITY_SRC:=		$(addprefix $(UTILITY)/,$(UTILITY_SRC))

SRCCOMMON+=		$(UTILITY_SRC)
