##
## Makefile for  in /home/ansel_l/Documents/Pfa/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Jan 30 11:21:32 2014 laurent ansel
## Last update Thu Jan 30 12:23:19 2014 laurent ansel
##

SRCCOMMON+=		$(JSON)/JsonFile.cpp
