##
## Makefile for  in /home/ansel_l/Documents/Pfa/work/Common
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Fri Nov 29 15:35:27 2013 laurent ansel
## Last update Fri Nov 29 15:35:44 2013 laurent ansel
##

SRCCOMMON +=			$(HEADER)/Header.cpp
