##
## Makefile<3> for  in /home/ansel_l/Documents/Pfa/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Nov 28 19:36:25 2013 laurent ansel
## Last update Fri Dec 13 17:41:29 2013 laurent ansel
##

SOURCESERVER=		$(SERVER_SRC)/Server
CODEBREAKER=		$(SERVER_SRC)/CodeBreaker
CLIENTMANAGER=		$(SERVER_SRC)/ClientManager

include			$(SOURCESERVER)/Makefile
include			$(CODEBREAKER)/Makefile
include			$(CLIENTMANAGER)/Makefile
