##
## Makefile<3> for  in /home/ansel_l/Documents/Pfa/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Nov 28 19:36:25 2013 laurent ansel
## Last update Wed Jan 29 16:11:12 2014 antoine maitre
##

SOURCESERVER=		$(SERVER_SRC)/Server
CODEBREAKER=		$(SERVER_SRC)/CodeBreaker
CLIENTMANAGER=		$(SERVER_SRC)/ClientManager
CHAT=			$(SERVER_SRC)/Chat
MAP=			$(SERVER_SRC)/Map
BATTLESERV=		$(SERVER_SRC)/Battle

include			$(SOURCESERVER)/Makefile
include			$(CODEBREAKER)/Makefile
include			$(CLIENTMANAGER)/Makefile
include			$(CHAT)/Makefile
include			$(MAP)/Makefile
include			$(BATTLESERV)/Makefile
