##
## Makefile for  in /home/ansel_l/Documents/Pfa/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Thu Nov 28 16:45:35 2013 laurent ansel
## Last update Thu Nov 28 19:36:15 2013 laurent ansel
##

SRCSERVER +=		$(SERVER_SRC)/main.cpp

include			$(SERVER_SRC)/Makefile

SERVER_INCLUDES=	-I $(SERVER)/include
