##
## Makefile for  in /home/ansel_l/Documents/Pfa/work/Server/include
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sun Dec  1 14:59:50 2013 laurent ansel
## Last update Tue Jan 28 13:27:06 2014 laurent ansel
##

SRCSERVER +=	$(CLIENTMANAGER)/Client.cpp		\
		$(CLIENTMANAGER)/ClientUpdater.cpp	\
		$(CLIENTMANAGER)/ClientManager.cpp	\
		$(CLIENTMANAGER)/ReadWriteAction.cpp	\
