##
## Makefile for  in /home/ansel_l/Documents/Pfa/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Jan 28 13:26:53 2014 laurent ansel
## Last update Tue Jan 28 13:27:16 2014 laurent ansel
##

SRCSERVER +=	$(CHAT)/Chat.cpp		\
