##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Fri Jan 24 14:53:15 2014 antoine maitre
##

SRCCOMMON+=		$(ZONE)/Case.cpp
SRCCOMMON+=		$(ZONE)/Zone.cpp

