##
## Makefile<4> for  in /home/maresc_g/Projets/en_cours/linumon/MMO/Client
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Jan 24 13:15:25 2014 guillaume marescaux
## Last update Fri Jan 24 14:00:26 2014 guillaume marescaux
##

SRCCLIENT +=		$(CLIENT_SRC)/main.cpp
SRCCLIENT +=		$(CLIENT_SRC)/Client.cpp

CORE=			$(CLIENT_SRC)/Core

include			$(CORE)/Makefile
