##
## Makefile<6> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:21:24 2013 laurent ansel
## Last update Tue Nov 26 00:31:11 2013 alexis mestag
##

SRCCOMMON +=		$(THREAD)/UnixThread.cpp		\
			$(THREAD)/PthreadCondition.cpp
