##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Wed Mar  5 12:37:07 2014 laurent ansel
## Last update Wed Mar 19 14:36:05 2014 alexis mestag
##

SRCSERVER +=	$(LOADER)/MobModelLoader.cpp		\
		$(LOADER)/JobModelLoader.cpp		\
		$(LOADER)/StuffLoader.cpp		\
		$(LOADER)/ConsumableLoader.cpp		\
		$(LOADER)/SpellLoader.cpp		\
		$(LOADER)/TalentModelLoader.cpp		\
		$(LOADER)/HealLoader.cpp		\
		$(LOADER)/RessourceLoader.cpp		\
		$(LOADER)/AuthorizedStatKeysLoader.cpp	\
		$(LOADER)/TalentTreeLoader.cpp		\
		$(LOADER)/LoaderManager.cpp
