##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Wed Mar  5 12:37:07 2014 laurent ansel
## Last update Fri Mar 14 15:41:40 2014 laurent ansel
##

SRCSERVER +=	$(LOADER)/MobModelLoader.cpp	\
		$(LOADER)/JobModelLoader.cpp	\
		$(LOADER)/StuffLoader.cpp	\
		$(LOADER)/ConsumableLoader.cpp	\
		$(LOADER)/CarcassLoader.cpp	\
		$(LOADER)/SpellLoader.cpp	\
		$(LOADER)/TalentModelLoader.cpp	\
		$(LOADER)/HealLoader.cpp	\
		$(LOADER)/RessourceLoader.cpp	\
		$(LOADER)/AuthorizedStatKeysLoader.cpp	\
		$(LOADER)/LoaderManager.cpp
