##
## Makefile for  in /home/ansel_l/Documents/Pfa/linumon/MMO
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Wed Mar  5 12:37:07 2014 laurent ansel
## Last update Wed Mar  5 15:17:07 2014 laurent ansel
##

SRCSERVER +=	$(LOADER)/MobModelLoader.cpp	\
		$(LOADER)/LoaderManager.cpp
