##
## Makefile for Makefile in /home/mestag_a/Documents/Projets/Tek3/PFA/linumon/MMO
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Tue Dec  3 13:09:41 2013 alexis mestag
## Last update Tue Dec  3 13:10:25 2013 alexis mestag
##

STATS_SRC=		Stat.cpp	\
			Stats.cpp

STATS_SRC:=		$(addprefix $(STATS)/,$(STATS_SRC))

SRCCOMMON+=		$(STATS_SRC)
