##
## Makefile<3> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 15:43:44 2013 laurent ansel
## Last update Wed Mar  5 12:39:33 2014 laurent ansel
##

SRCSERVER +=	$(MAP)/Map.cpp
