##
## Makefile<3> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 15:43:44 2013 laurent ansel
## Last update Fri Jan 24 16:38:19 2014 antoine maitre
##

SRCSERVER +=	$(MAP)/Map.cpp
